-- CreateEnum
CREATE TYPE "OwaspCategory" AS ENUM ('A01_BROKEN_ACCESS_CONTROL', 'A02_CRYPTOGRAPHIC_FAILURES', 'A03_INJECTION', 'A04_INSECURE_DESIGN', 'A05_SECURITY_MISCONFIGURATION', 'A06_VULNERABLE_COMPONENTS', 'A07_AUTH_FAILURES', 'A08_SOFTWARE_DATA_INTEGRITY_FAILURES', 'A09_LOGGING_MONITORING_FAILURES', 'A10_SSRF');

-- CreateEnum
CREATE TYPE "Severity" AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL');

-- AlterTable
ALTER TABLE "review_items" ADD COLUMN     "owaspCategory" "OwaspCategory",
ADD COLUMN     "severity" "Severity";
