// backend/src/services/report.service.ts
import { OWASP_LABELS } from "../lib/owaspLabels";

interface ReviewItemForReport {
  type: string;
  title: string;
  description: string;
  line: number | null;
  suggestedCode: string | null;
  owaspCategory: string | null;
  severity: string | null;
}

interface ReviewForReport {
  id: string;
  language: string;
  reviewerLevel: string;
  score: number | null;
  summary: string | null;
  createdAt: Date;
  items: ReviewItemForReport[];
}

const TYPE_ICON: Record<string, string> = {
  ERROR: "🔴",
  SECURITY: "🔒",
  WARNING: "🟡",
  SUGGESTION: "💡",
};

export const generateMarkdownReport = (review: ReviewForReport): string => {
  const lines: string[] = [];

  lines.push(`# Code Review Report`);
  lines.push("");
  lines.push(`**Language:** ${review.language}  `);
  lines.push(`**Reviewed as:** ${review.reviewerLevel.toLowerCase()}  `);
  lines.push(`**Date:** ${review.createdAt.toISOString().split("T")[0]}  `);
  if (review.score !== null) {
    lines.push(`**Score:** ${review.score}/100  `);
  }
  lines.push("");

  if (review.summary) {
    lines.push(`## Summary`);
    lines.push("");
    lines.push(review.summary);
    lines.push("");
  }

  const securityItems = review.items.filter((i) => i.type === "SECURITY");
  if (securityItems.length > 0) {
    const critical = securityItems.filter(
      (i) => i.severity === "CRITICAL" || i.severity === "HIGH",
    ).length;
    lines.push(`## Security Overview`);
    lines.push("");
    lines.push(`- Total security findings: ${securityItems.length}`);
    lines.push(`- High/Critical severity: ${critical}`);
    lines.push("");
  }

  lines.push(`## Issues (${review.items.length})`);
  lines.push("");

  for (const item of review.items) {
    const icon = TYPE_ICON[item.type] ?? "•";
    lines.push(`### ${icon} ${item.title}`);
    lines.push("");

    const tags: string[] = [item.type];
    if (item.owaspCategory && OWASP_LABELS[item.owaspCategory]) {
      tags.push(`OWASP ${OWASP_LABELS[item.owaspCategory].code}`);
    }
    if (item.severity) tags.push(`Severity: ${item.severity}`);
    if (item.line) tags.push(`Line ${item.line}`);
    lines.push(`_${tags.join(" · ")}_`);
    lines.push("");

    lines.push(item.description);
    lines.push("");

    if (item.suggestedCode) {
      lines.push("```" + review.language);
      lines.push(item.suggestedCode);
      lines.push("```");
      lines.push("");
    }
  }

  lines.push("---");
  lines.push(`_Generated by AI Code Review · ${new Date().toISOString()}_`);

  return lines.join("\n");
};
