// frontend/src/app/(app)/review/[id]/report/page.tsx
"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams } from "next/navigation";
import { reviewApi } from "@/lib/apiClient";
import { Printer, ArrowLeft } from "lucide-react";
import { OWASP_LABELS, SEVERITY_STYLES } from "@/lib/owasp";

interface ReviewItem {
  id: string;
  type: "ERROR" | "WARNING" | "SUGGESTION" | "SECURITY";
  title: string;
  description: string;
  line: number | null;
  suggestedCode: string | null;
  owaspCategory: string | null;
  severity: string | null;
}

interface Review {
  id: string;
  language: string;
  reviewerLevel: string;
  score: number | null;
  summary: string | null;
  createdAt: string;
  items: ReviewItem[];
}

export default function ReportPrintPage() {
  const params = useParams();
  const [review, setReview] = useState<Review | null>(null);

  useEffect(() => {
    reviewApi
      .getById(params.id as string)
      .then((data) => setReview(data.review));
  }, [params.id]);

  if (!review) {
    return <div className="p-8 text-gray-400">Loading report...</div>;
  }

  return (
    <div className="max-w-3xl mx-auto p-8 bg-white text-gray-900">
      {/* Кнопка печати — скрывается при печати через print:hidden */}
      <div className="print:hidden mb-6 flex items-center justify-between">
        <Link
          href={`/review/${params.id}`}
          className="flex items-center gap-2 text-sm text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100 transition-colors"
        >
          <ArrowLeft size={16} />
          Back to review
        </Link>

        <button
          onClick={() => window.print()}
          className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700"
        >
          <Printer size={16} />
          Save as PDF / Print
        </button>
      </div>

      <h1 className="text-2xl font-bold mb-1">Code Review Report</h1>
      <p className="text-sm text-gray-500 mb-6">
        {review.language} · {review.reviewerLevel} reviewer ·{" "}
        {new Date(review.createdAt).toLocaleDateString()}
        {review.score !== null && ` · Score: ${review.score}/100`}
      </p>

      {review.summary && (
        <div className="mb-6">
          <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500 mb-1">
            Summary
          </h2>
          <p className="text-sm">{review.summary}</p>
        </div>
      )}

      <h2 className="text-sm font-semibold uppercase tracking-wide text-gray-500 mb-3">
        Issues ({review.items.length})
      </h2>

      <div className="space-y-4">
        {review.items.map((item) => (
          <div
            key={item.id}
            className="border border-gray-200 rounded-lg p-4 break-inside-avoid"
          >
            <div className="flex items-center gap-2 flex-wrap mb-1.5">
              <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-gray-100">
                {item.type}
              </span>
              {item.owaspCategory && OWASP_LABELS[item.owaspCategory] && (
                <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-purple-50 text-purple-700">
                  OWASP {OWASP_LABELS[item.owaspCategory].code}
                </span>
              )}
              {item.severity && SEVERITY_STYLES[item.severity] && (
                <span className="text-xs font-medium px-2 py-0.5 rounded-full bg-gray-100">
                  {SEVERITY_STYLES[item.severity].label}
                </span>
              )}
              {item.line && (
                <span className="text-xs text-gray-400">Line {item.line}</span>
              )}
            </div>
            <p className="font-medium text-sm mb-1">{item.title}</p>
            <p className="text-sm text-gray-600">{item.description}</p>
            {item.suggestedCode && (
              <pre className="mt-2 bg-gray-50 border border-gray-200 rounded p-2 text-xs overflow-x-auto">
                {item.suggestedCode}
              </pre>
            )}
          </div>
        ))}
      </div>

      <p className="text-xs text-gray-400 mt-8 pt-4 border-t border-gray-200">
        Generated by AI Code Review · {new Date().toLocaleString()}
      </p>
    </div>
  );
}
